fastlane_version "2.38.1"

generated_fastfile_id "b2217ca0-6074-48b7-8bbe-05d2469de0e8"

default_platform :android

platform :android do
  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "assembleRelease")

    crashlytics(
      api_token: "bf8d03baf646d8880e7c4ed98b9b9785503609f6",
      # build_secret has to be provided throught environment variable CRASHLYTICS_BUILD_SECRET
    )
  end

  # TODO deployment to Google Play not done yet
  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    supply
  end
end
